/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SRC_MSG_PB_H_INCLUDED
#define PB_SRC_MSG_PB_H_INCLUDED
#include "Nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DataMessage {
    float encoder_one;
    float encoder_two;
    float encoder_three;
    float encoder_four;
    float x;
    float y;
    float h;
    bool tag;
    uint32_t rx;
    uint32_t ry;
    uint32_t bx;
    uint32_t by;
} DataMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DataMessage_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define DataMessage_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DataMessage_encoder_one_tag              1
#define DataMessage_encoder_two_tag              2
#define DataMessage_encoder_three_tag            3
#define DataMessage_encoder_four_tag             4
#define DataMessage_x_tag                        5
#define DataMessage_y_tag                        6
#define DataMessage_h_tag                        7
#define DataMessage_tag_tag                      8
#define DataMessage_rx_tag                       9
#define DataMessage_ry_tag                       10
#define DataMessage_bx_tag                       11
#define DataMessage_by_tag                       12

/* Struct field encoding specification for nanopb */
#define DataMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    encoder_one,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    encoder_two,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    encoder_three,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    encoder_four,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 5) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 6) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 7) \
X(a, STATIC,   SINGULAR, BOOL,     tag,               8) \
X(a, STATIC,   SINGULAR, UINT32,   rx,                9) \
X(a, STATIC,   SINGULAR, UINT32,   ry,               10) \
X(a, STATIC,   SINGULAR, UINT32,   bx,               11) \
X(a, STATIC,   SINGULAR, UINT32,   by,               12)
#define DataMessage_CALLBACK NULL
#define DataMessage_DEFAULT NULL

extern const pb_msgdesc_t DataMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DataMessage_fields &DataMessage_msg

/* Maximum encoded size of messages (where known) */
#define DataMessage_size                         61
#define SRC_MSG_PB_H_MAX_SIZE                    DataMessage_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
